repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: name-tests-test
      - id: pretty-format-json
        name: pretty format json
        entry: pretty-format-json
        args:
          - "--autofix"
          - "--indent=4"
          - "--no-ensure-ascii"

  - repo: https://github.com/grantjenks/blue
    rev: v0.9.1
    hooks:
      - id: blue
        name: blue
        entry: blue
        language: python
        language_version: python3
        require_serial: true
        types_or: [ python, pyi ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --force-exclude
        language: python
        language_version: python3
        types_or: [ python, pyi ]
        args: [ --fix ]
        require_serial: true
        minimum_pre_commit_version: "2.9.2"

      - id: ruff-format
        name: ruff-format
        entry: ruff format --force-exclude
        language: python
        language_version: python3
        types_or: [ python, pyi ]
        require_serial: true
        minimum_pre_commit_version: "2.9.2"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.10.1'
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        language_version: python3
        types_or: [ python, pyi ]
        args: [ "--ignore-missing-imports", "--scripts-are-modules", "--check-untyped-defs"]
        require_serial: true
        additional_dependencies: [tokenize-rt==3.2.0]
        minimum_pre_commit_version: '2.9.2'
